version: '2'
services:
    modulo04_practica02_jhipster-mysql:
        container_name: modulo04_practica02_jhipster-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/modulo04_practica02_jhipster/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=modulo04_practica02_jhipster
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
